# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        cd src
        go build -v ./...

    - name: Test
      run: |
        cd src
        go test -v ./...

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: sachinparihar/go-weather-app
        tags: v1, latest
        registry: docker.io
        dockerfile: ./src/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Azure VM
      env:
          VM_IP_ADDRESS: $4.236.157.153
          HOST_PORT: 8080
          CONTAINER_PORT: 80
          IMAGE_NAME: go-weather-app
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
      run: |
          sudo apt-get install -y sshpass
          sshpass -p $VM_PASSWORD ssh Az2-user@$4.236.157.153 "docker pull sachinparihar/go-weather-app"
          sshpass -p $VM_PASSWORD ssh Az2-user@$4.236.157.153 "docker run -p 8080:8080 -d sachinparihar/go-weather-app"
